/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 gun_targets.glb 
Author: FrodoUndead (https://sketchfab.com/FrodoUndead)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gun-targets-eb9fbe283faa41ef8685359a0769d303
Title: Gun Targets
*/

import React, { useRef } from "react";
import { Box, useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

export function Targets() {
  const { nodes, materials }: any = useGLTF("/targets.glb");
  return (
    <group dispose={null} scale={0.35}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.311}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <RigidBody type="fixed" colliders="trimesh">
            <group position={[-75.509, 0, 0]}>
              <mesh
                geometry={nodes.Object_8.geometry}
                material={materials.Targets}
              />
              <mesh
                geometry={nodes.Object_10.geometry}
                material={materials.Targets}
              />
              <mesh
                geometry={nodes.Object_12.geometry}
                material={materials.Targets}
              />
            </group>
          </RigidBody>
          <Box args={[15, 0.5, 2]} position={[0.003, 35, -305.061]}>
            <meshStandardMaterial color={"red"} />
          </Box>
          <RigidBody type="fixed" colliders="trimesh">
            <mesh
              geometry={nodes.Moveable_target.geometry}
              material={materials.Targets}
              position={[0.003, 28.3, -305.061]}
            />
          </RigidBody>
          <RigidBody type="fixed" colliders="trimesh">
            <group>
              <group position={[-105.543, 0, 0]}>
                <mesh
                  geometry={nodes.Object_4.geometry}
                  material={materials.Targets}
                />
                <mesh
                  geometry={nodes.Object_6.geometry}
                  material={materials.Targets}
                />
              </group>
              <mesh
                geometry={nodes.Object_20.geometry}
                material={materials.Targets}
                position={[-38.032, 0, 0]}
              />
              <mesh
                geometry={nodes.Object_22.geometry}
                material={materials.Targets}
                position={[-75.509, 0, 0]}
              />
              <mesh
                geometry={nodes.Object_18.geometry}
                material={materials.Targets}
                scale={-1.832}
              />
            </group>
          </RigidBody>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/targets.glb");
